name: CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1.4.4
      with:
        node-version: 14.x
    - run: npm i && npm run lint

  MinecraftServer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mcVersion: ['1.8.8', '1.9.4', '1.10.2', '1.11.2', '1.12.2', '1.13.2', '1.14.4', '1.15.2', '1.16.5']
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1.4.4
      with:
        node-version: 14.x
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
        java-package: jre
    - name: Install Dependencies
      run: npm install
    - name: Install Prismarine-Viewer dependencies
      run: |
        sudo apt update
        sudo apt-get install ffmpeg xvfb -y
    - name: Start Tests
      run: xvfb-run -s "-ac -screen 0 1280x1024x24" npm run mocha_test -- -g ${{ matrix.mcVersion }}
      env:
        USE_PVIEWER_IN_TESTS: 'y'
    - name: rename video
      run: mv output.mp4 ${{ matrix.mcVersion }}.mp4
    - uses: actions/upload-artifact@v2
      with:
        name: videos
        path: ${{ matrix.mcVersion }}.mp4
